//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_POST
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string UserId { get; set; }
        public int TopicId { get; set; }
    
        public virtual FORUM_TOPIC FORUM_TOPIC { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
