//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_TOPIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORUM_TOPIC()
        {
            this.FORUM_POST = new HashSet<FORUM_POST>();
        }
    
        public int Id { get; set; }
        public string TopicName { get; set; }
        public string TopicDescription { get; set; }
        public System.DateTime TopicDateTime { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORUM_POST> FORUM_POST { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
